<?php

namespace Flare\ImageMap;

/**
 * Lifecycle functions for the plugin
 */
class AssetPath {

	const ASSETDIR = 'assets/build/';

	/** @var string $name The base filename of the asset. */
	protected $name;

	/**
	 * @param string $name The base filename of the asset.
	 */
	public function __construct( string $name ) {
		$this->name = $name;
	}

		/**
		 * Load the dependencies from the loader file generated by wp-scripts.
		 *
		 * @return Array|false The dependencies and version of the asset,
		 *    or false if dependencies could not be loaded.
		 * @since 0.1.0
		 **/
	public function get_dependencies() {
		$path = plugin_dir_path( __DIR__ ) . self::ASSETDIR . $this->name . '.asset.php';

		if ( ! file_exists( $path ) ) {
			return false;
		}

		return require $path;
	}

	/**
	 * Get the url where the built scripts can be found.
	 *
	 * @param string $ext The extension of the file to return.
	 * @return string The url
	 * @since 0.1.0
	 **/
	public function get_url( $ext ) {
		return plugins_url( self::ASSETDIR . $this->name . '.' . $ext, __DIR__ );
	}

	/**
	 * Get the path to the build folder.
	 *
	 * @param string $ext The extension of the file to return.
	 * @return string Path
	 * @since 0.1.0
	 **/
	public function get_path( $ext ) {
		return plugin_dir_path( __DIR__ ) . self::ASSETDIR . $this->name . '.' . $ext;
	}
}
