<?php

namespace Flare\ImageMap;

/**
 * Asset loader for assets generated by wp-scripts.
 */
class WpScriptsAsset {

	const ASSETDIR = 'assets/build/';

	/** @var string $path The base filename of the asset. */
	protected $path;

	/** @var string $handle The handle to use when registering a script or style. */
	protected $handle;

	/** @var array $meta Script meta generated by wp-scripts */
	protected $meta;

	/** @var array<string> $deps Dependencies to register for this script on top of the ones generated by wp-scripts. */
	protected $deps;

	/**
	 * @param string        $path The base filename of the asset.
	 * @param string        $handle The handle to use when registering a script or style.
	 * @param array<string> $deps Dependencies to register for this script on top of the ones generated by wp-scripts.
	 */
	public function __construct( string $path, string $handle, array $deps = array() ) {
		$this->path   = $path;
		$this->handle = $handle;
		$this->deps   = $deps;
	}

	/**
	 * Get the url where the built scripts can be found.
	 *
	 * @param string $ext The extension of the file to return.
	 * @return string The url
	 * @since 0.1.0
	 **/
	public function get_url( $ext ) {
		return plugins_url( self::ASSETDIR . $this->path . ( $ext ? '.' . $ext : '' ), __DIR__ );
	}

	/**
	 * Get the path to the build folder.
	 *
	 * @param string $ext The extension of the file to return.
	 * @return string Path
	 * @since 0.1.0
	 **/
	public function get_path( $ext = null ) {
		return plugin_dir_path( __DIR__ ) . self::ASSETDIR . $this->path . ( $ext ? '.' . $ext : '' );
	}

	/**
	 * Load the dependencies from the loader file generated by wp-scripts.
	 *
	 * @return array The dependencies and version of the asset.
	 * @since 0.1.0
	 **/
	public function get_meta() {
		if ( ! $this->meta ) {
			$path = $this->get_path( 'asset.php' );

			if ( ! file_exists( $path ) ) {
				return array();
			}

			$this->meta = require $path;
		}

		return $this->meta;
	}

	/**
	 * Register the script.
	 *
	 * @return boolean Whether the registration was successful.
	 * @since 0.1.0
	 **/
	public function register_script() {
		$meta = $this->get_meta();
		if ( ! is_array( $meta['dependencies'] ) ) {
			return false;
		}

		$url = $this->get_url( 'js' );

		$success = wp_register_script(
			$this->handle,
			$url,
			array_merge( $this->deps, $meta['dependencies'] ),
			$meta['version'],
			true
		);

		return $success;
	}

	/**
	 * Enqueue the asset css file.
	 *
	 * @return boolean Whether the registration was successful.
	 * @since 0.1.0
	 **/
	public function enqueue_style() {
		$meta = $this->get_meta();
		if ( ! $meta['version'] ) {
			return false;
		}

		if ( ! file_exists( $this->get_path( 'css' ) ) ) {
			return false;
		}

		wp_enqueue_style(
			$this->handle,
			$this->get_url( 'css' ),
			array( 'wp-components' ),
			$meta['version']
		);

		return true;
	}
}
